hub:
  serverUrl: 'http://localhost:4060'
  roomToken: '12345678'
  roomName: 'Bebert Control Room'
  deviceId: 'satelles-python-bebert-dev'
  deviceName: 'Python Satelles (dev)'

commands:
  - debug
  - sensor

misc:
  debugSocket: false
